[connections.snowflake]
type = "snowflake"

account = "xc48564"
user = "younes"
password = "Snowflake.83300"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
