[connections.snowflake]
account = "XC48564"
user = "YOUNES"
password = "Snowflake.83300"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
